#!/usr/bin/env bash
set -euo pipefail

REGION="${AWS_REGION:-us-west-2}"
TABLE_NAME="LogisticsOffers"
ROLE_NAME="LogisticsLambdaRole"
LAMBDA_NAME="LogisticsQueryOffers"
PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
LAMBDA_DIR="${PROJECT_DIR}/lambda"
ENV_FILE="${PROJECT_DIR}/.env"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
CALLER_ARN=$(aws sts get-caller-identity --query Arn --output text)

if [[ "$CALLER_ARN" == *":root" ]]; then
  echo "❌ Refusing to deploy as root. Switch to an IAM user."
  exit 1
fi

echo "→ Account: $ACCOUNT_ID  Region: $REGION  As: $CALLER_ARN"

# 1. DynamoDB table
echo ""
echo "→ DynamoDB table: $TABLE_NAME"
if aws dynamodb describe-table --table-name "$TABLE_NAME" --region "$REGION" >/dev/null 2>&1; then
  echo "  Already exists, skipping."
else
  aws dynamodb create-table \
    --table-name "$TABLE_NAME" \
    --region "$REGION" \
    --attribute-definitions \
        AttributeName=offer_id,AttributeType=S \
        AttributeName=origin,AttributeType=S \
    --key-schema AttributeName=offer_id,KeyType=HASH \
    --global-secondary-indexes \
        "IndexName=OriginIndex,KeySchema=[{AttributeName=origin,KeyType=HASH}],Projection={ProjectionType=ALL},ProvisionedThroughput={ReadCapacityUnits=5,WriteCapacityUnits=5}" \
    --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
    >/dev/null
  echo "  Waiting for ACTIVE state..."
  aws dynamodb wait table-exists --table-name "$TABLE_NAME" --region "$REGION"
  echo "  Created."
fi

# 2. IAM role for Lambda
echo ""
echo "→ IAM role: $ROLE_NAME"
TRUST='{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":"lambda.amazonaws.com"},"Action":"sts:AssumeRole"}]}'

if aws iam get-role --role-name "$ROLE_NAME" >/dev/null 2>&1; then
  echo "  Already exists."
else
  aws iam create-role \
    --role-name "$ROLE_NAME" \
    --assume-role-policy-document "$TRUST" \
    >/dev/null
  echo "  Created."
fi

aws iam attach-role-policy --role-name "$ROLE_NAME" \
  --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
aws iam attach-role-policy --role-name "$ROLE_NAME" \
  --policy-arn arn:aws:iam::aws:policy/AmazonDynamoDBReadOnlyAccess
echo "  Policies attached."

echo "  Sleeping 12s for IAM propagation..."
sleep 12

# 3. Package Lambda
echo ""
echo "→ Packaging Lambda..."
cd "$LAMBDA_DIR"
rm -f function.zip
zip -q function.zip lambda_function.py
cd "$PROJECT_DIR"
echo "  Created lambda/function.zip"

# 4. Deploy / update Lambda
echo ""
echo "→ Lambda function: $LAMBDA_NAME"
ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${ROLE_NAME}"

if aws lambda get-function --function-name "$LAMBDA_NAME" --region "$REGION" >/dev/null 2>&1; then
  echo "  Updating code..."
  aws lambda update-function-code \
    --function-name "$LAMBDA_NAME" \
    --region "$REGION" \
    --zip-file "fileb://${LAMBDA_DIR}/function.zip" \
    >/dev/null
  echo "  Updated."
else
  echo "  Creating..."
  aws lambda create-function \
    --function-name "$LAMBDA_NAME" \
    --region "$REGION" \
    --runtime python3.11 \
    --role "$ROLE_ARN" \
    --handler lambda_function.lambda_handler \
    --zip-file "fileb://${LAMBDA_DIR}/function.zip" \
    --timeout 10 \
    >/dev/null
  echo "  Created."
fi

# 5. Write .env
cat > "$ENV_FILE" <<EOF
# Auto-generated by 02_deploy_infra.sh
export AWS_REGION=${REGION}
export AWS_PROFILE=${AWS_PROFILE:-logistics-dev}
export DDB_TABLE=${TABLE_NAME}
export LAMBDA_NAME=${LAMBDA_NAME}
export BEDROCK_MODEL_ID=us.anthropic.claude-sonnet-4-6
EOF

echo ""
echo "✓ Infrastructure deployed."
echo "  Config written to: $ENV_FILE"
echo ""
echo "Next:"
echo "  source .env"
echo "  python infra/03_seed_data.py"
echo "  ./infra/04_verify.sh"
